---
- hosts: dev
  remote_user: root
  become: yes
  roles:
    - role: oathkeeper-role
      become: yes
  vars:
    oath_version: v0.38.9-beta.1
    oath_install_path: /var/lib/oathkeeper
    oath_service_user: root
    oath_service_group: root
    oath_proxy_port: 9500
    oath_api_port: 9600
    oath_redirect_enabled: true
    oath_redirect_url: https://tokopedia.com
    oath_noop_enabled: true
    oath_issuer_url: http://localhost:9500/
    oath_rule_match_url: <http|https>://<.*>/<.*>
